## Universal Docker Compose
## to run specific service:
## docker compose up -d <service-name>

version: '3.9'
services:
  redis_basic_1:
    image: redis:latest
    container_name: redis_basic_1
    ports:
      - 6379:6379

  ## with config
  redis_basic_2:
    image: redis:latest
    container_name: redis_basic_2
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf # command redis untuk menunjukan lokasi confignya
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

  ## with command
  redis_basic_3:
    image: redis:latest
    container_name: redis_basic_3
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf # command redis untuk menunjukan lokasi confignya
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./command:/usr/local/etc/command

  ## with security
  redis_basic_4:
    image: redis:latest
    container_name: redis_basic_4
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf # command redis untuk menunjukan lokasi confignya
    volumes:
      - ./config/redis-security.conf:/usr/local/etc/redis/redis.conf
  redis_client_4:
    container_name: redis_client_4
    image: redis:latest
